# Generated by Django 5.0 on 2024-02-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
