# Generated by Django 5.0 on 2024-02-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0002_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
